import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../../components/header";
import MainBanner from "./routes/home/banner";
import JoinCommunity from "./routes/home/joinCommunity";
import YouTube from "./routes/home/youTube";
import About from "./routes/home/about";
import Redefine from "./routes/home/redefine";
import OrderYourBook from "./routes/home/orderYourBook";
import Achieving from "./routes/home/achieving";
import Footer from "../../components/footer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="landing-page-main">
          <MainBanner />
          <JoinCommunity />
          <YouTube />
          <About />
          <Redefine />
          <OrderYourBook />
          <Achieving />
        </div>
        <Footer />
      </main>
    </>
  );
}
